added follow model, serializer and views(in author and user), also fixed permission for author and change error language on ru
DenisHrtn/it_bel_project pull request #55
Opened 2023-08-01 14:12 UTC by SerezhaK

Пермишенны пока что не полноценно исправлены, убрал лишь требование AdminIs

UPD: С пермишеннами все готово

2023-08-01 20:25 UTC, Demianight requested changes

2023-08-01 20:25 UTC, Demianight commented on users/models/follow.py
> +        verbose_name_plural = 'Подписка'
plural это множественное число, то есть должны быть "Подписки"

2023-08-01 20:25 UTC, Demianight commented on users/serializers/follow.py
> +                'You cannot subscribe on yourself.'
Мы отдаем ошибки в другом формате:
{'detail':  'error text'}
Найди примеры

2023-08-01 20:25 UTC, Demianight commented on users/views/user.py
> +        authors = Follow.objects.filter(follower=user.user_id)
Так как follower это связь ForeingKey к User, то лучше указывать там не айди, а самого User

2023-08-01 20:25 UTC, Demianight commented on users/views/user.py
> +        authors = Follow.objects.filter(follower=user.user_id)
Ты фильтруешь подписки, так что перменная никак не может называться authors

2023-08-01 20:25 UTC, Demianight commented on users/views/user.py
> +        detail=True,
Почему? Разве на профиль нам нужен id автора? Для этого у нас есть /users/{user_id}/

2023-08-02 09:16 UTC, SerezhaK commented on users/views/user.py
> +        detail=True,
упс я тестил и забыл

2023-08-02 15:05 UTC, Demianight requested changes

2023-08-02 15:05 UTC, Demianight commented on news/permissions/AuthorOrReadOnlyNews.py
> +from rest_framework import permissions
Мне как то не очень нравится название файла((
У них же различие в коментариях и новостях, я бы так файлы и назвал
Ну и + ко всему файлы не называются в CamelCase

2023-08-02 15:05 UTC, Demianight commented on news/permissions/AuthorOrReadOnlyComments.py
> +from rest_framework import permissions
Мне как то не очень нравится название файла((
У них же различие в коментариях и новостях, я бы так файлы и назвал
Ну и + ко всему файлы не называются в CamelCase

2023-08-02 15:05 UTC, Demianight commented on tests/follows/test_follows.py
> +        self.client_for_athor = APIClient()
Опечатка

2023-08-02 15:05 UTC, Demianight commented on users/permissions/AuthorOwnerOrReadOnly.py
> +from rest_framework import permissions
Мне как то не очень нравится название файла((
Ну и + ко всему файлы не называются в CamelCase

2023-08-02 15:05 UTC, Demianight commented on users/permissions/IsModerator.py
> +from rest_framework import permissions
Мне как то не очень нравится название файла((
Ну и + ко всему файлы не называются в CamelCase

2023-08-02 15:05 UTC, Demianight commented on users/permissions/IsSuperUser.py
> +from rest_framework import permissions
Мне как то не очень нравится название файла((
Ну и + ко всему файлы не называются в CamelCase

2023-08-02 15:05 UTC, Demianight commented on users/permissions/UserOwnerOrReadOnly.py
> +from rest_framework import permissions
Мне как то не очень нравится название файла((
Ну и + ко всему файлы не называются в CamelCase

2023-08-02 15:05 UTC, Demianight commented on users/models/follow.py
> +    follower = models.ForeignKey(
У нас на проекте принято указывать id явно, +follow_id

2023-08-02 15:05 UTC, Demianight commented on users/serializers/follow.py
> +    def validate(self, data: dict):
Молодец, обошел мою ошибку))

2023-08-02 15:05 UTC, Demianight commented on users/views/author.py
> +            'author': pk,
Вот сейчас посмотрел, мы же и так находим автора, можно указывать туда не pk, а целую модель, так выглядит более интуитивно-понятно.
То же самое со строчкой ниже

2023-08-02 15:05 UTC, Demianight commented on users/views/author.py
> +    def unfollow(self, request: HttpRequest, pk: int):
Были претензии, но после собственного research-а понял что все работает как надо)
Молодец) Я бы написал хуже

2023-08-02 15:05 UTC, Demianight commented on users/views/author.py
> +        followers = Follow.objects.filter(author=pk)
1. См. строка 47
2. Follow filter возвращает подписки, а не подписчиков
3. В этой функции ты должен вернуть всех подписчиков, то есть список из User, а возвращаешь ты объекты Follow, подумай как это разрулить. Просто в первом сценарии фронту придется намного легче, не придется для каждого подписчика отправлять дополнительные запросы, а от этого выгода и для нас - меньше долбёжки к БД

2023-08-02 15:05 UTC, Demianight commented on users/views/user.py
> +    @action(
Тут все хорошо)

2023-08-02 17:40 UTC, mazazyrik commented on users/serializers/follow.py
> +                'You cannot subscribe on yourself.'
пример очевиден
я детаил

2023-08-03 15:31 UTC, merged