Tag added
DenisHrtn/it_bel_project pull request #72
Opened 2023-08-21 20:26 UTC by mazazyrik

guys this is a biggest innovation since born of Steve jobs
pls check

2023-08-21 20:36 UTC, Demianight requested changes
Слава богу что у нас есть ревьюер.

А то это золото могло попасть в прод

2023-08-21 20:36 UTC, Demianight commented on fixtures/tag.json
> +[
Зачем в фикстуре с тегом другие модели?

2023-08-21 20:36 UTC, Demianight commented on news/models/news.py
> +    tags = models.ManyToManyField(
Я тебе говорил, если что - будешь править сам)))

2023-08-21 20:36 UTC, Demianight commented on news/models/tag.py
> +        verbose_name_plural = 'Тег'
Гений английского, что такое plural

2023-08-21 20:36 UTC, Demianight commented on news/models/tag.py
> +    slug = models.SlugField()
Я все время про slug забываю, а штука топовая, ставлю тебе лайк.

Где verbose_name?

2023-08-21 20:36 UTC, Demianight commented on fixtures/news.json
> +      "tags": "1"
Возможно Я что то путаю, но это не должен быть список из int?

2023-08-21 20:36 UTC, Demianight commented on news/views/news.py
> -
Чет как то не понял куда все удалилось. Удалилось - окей, а чего вьюсет то от миксина не наследуется?

2023-08-21 20:36 UTC, Demianight commented on news/views/tag.py
> +    pagination_class = None
:))))

2023-08-21 20:36 UTC, Demianight commented on tests/news/test_news.py
> +        self.tag = Tag.objects.get(pk=1)
Молодец, подлатал

2023-08-21 20:36 UTC, Demianight commented on tests/tag/test_tag.py
> +        self.name = Tag.objects.get(pk=1)
Почему name, это Tag?

2023-08-21 20:36 UTC, Demianight commented on tests/tag/test_tag.py
> +class TagTestCase(APITestCase):
Я чет не очень понял, а что за выборочные тесты для GET и DELETE? Где patch, put, get на detail? 
Чекай другие тесты

2023-08-23 18:31 UTC, mazazyrik commented on news/models/tag.py
> +    slug = models.SlugField()
оно тут явно не нужно, слаг автополе

2023-08-23 18:32 UTC, mazazyrik commented on fixtures/news.json
> +      "tags": "1"
мени ту мени же
по фк ссылка, а стр вызывает имя
все четко

2023-08-23 19:42 UTC, merged